### ISSUE TITLE
Issue 1: Search for cards

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Pegasus-Deck-Builder#1]
## ⚙️ Feature

Users will be able to find cards by name

## 📐 Plan

Create an interactive search feature that will be able to retrieve information on specific cards

## 🖼️ Wireframes

![Screenshot 2022-06-13 150826](https://user-images.githubusercontent.com/99226300/173457375-cd21e9dc-399e-4441-84f1-a04daf05b25c.jpg)
![Screenshot 2022-06-13 150935](https://user-images.githubusercontent.com/99226300/173457388-70b2c772-f407-4d51-9108-824c6c9d2ba7.jpg)

## ✅ Task List
- [x] Create a global variable named `Data` and assign it as an object with the properties of `view: search`, `decks: []`, `resultId: 1`.
- [x] Add a header row with the site logo and 2 buttons to the HTML.
- [x] Add a 'div[data-view="search"]' to the HTML.
- [x] Add a required search input and submit button in the search div.
- [x] Add an empty `div[id="search-results"]` to the HTML.
- [x] make sure page looks good on both desktop and mobile screens.
- [x] listen for 'submit' events on the submit button and:
    - [x] make an API request for cards by the name given in the input.
        - [x] if none exist, return an display that it doesn't have a match.
    - [x] create a DOM element to display all available variants of a card in rows of column-4ths along with the name of the card(centered on mobile) and:
        - [x] adds a `resultId` to each displayed item
        - [x] increments the `resultId` property in the data model
    - [x] append the new DOM elements as children of the empty `div[id="search-results"]` 
- [x] does not need to save search results when page refreshes
- [x] verify that every displayed receives an incrementing `resultId`
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
