### ISSUE TITLE
Issue 2: User can view detailed card information

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Pegasus-Deck-Builder#2]
## ⚙️ Feature

Users will be able to click on cards in search results to view a detailed display including card info and prices from multiple sources

## 📐 Functionality

give search results interactivity to change to a detailed view

## 🖼️ Wireframes

![Screenshot 2022-06-13 162933](https://user-images.githubusercontent.com/99226300/173700117-a4eca163-ad7f-435e-afb7-94eab65ecb7e.jpg)

## ✅ Task List

- [x] create a new `div[data-view: details]` in the HTML
- [x] define a function in `main.js` to swap views between `search` and `detail` 
- [x] listen for click events on each `div[column-fourth]` and pass swap function as callback
- [x] create layout for detail view in HTML under the details data-view
- [x] confirm there is a click button to swap back to the `search` view inside the detail layout
- [x] create a new global variable to contain the value of xhr response called $response
- [x] use the data from that variable to include image, name, and card type in detail display
- [x] in a separate box, include pricing data found in $response
- [x]  does not need to save search results when page refreshes
- [x] make sure detail view looks good on both desktop and mobile screens
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x]  Fix all errors.
