### ISSUE TITLE
Issue 3: User can save cards to specific decks

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Pegasus-Deck-Builder#3]
## ⚙️ Feature

Users will be able to select decks from a list and add cards from search results to those decks

## 📐 Functionality

add dropdown of deck list and a button to add card to the selected deck

## 🖼️ Wireframes

![Screenshot 2022-06-13 151215](https://user-images.githubusercontent.com/99226300/173464116-b6bedfc8-6daa-4943-974c-76ce48f7f3e3.jpg)
![2](https://user-images.githubusercontent.com/99226300/173464119-cd6d31f9-b7e3-427c-bdad-e817e4757648.jpg)
![Screenshot 2022-06-13 151432](https://user-images.githubusercontent.com/99226300/173464122-e926bdac-630c-4327-9681-2da67544e8c0.jpg)

## ✅ Task List

- [x] add a button to DOM tree for `searchResults` function with the `id=add-button` attribute 
- [x] create a new object literal inside `decks` in the data model with a `name` property and a `cards` property containing an empty array
- [x] add a property to the deck object called `nextCardId`
- [x] listen for click events on the add button and use a function to add data from the card including image into the data model as a callback
- [x] ensure that the data is saved into local storage
- [x] ensure that each card in the data model is assigned a `card-id`
- [x] increment the `card-id` with each new card
- [x] add modal to page to appear to confirm that a card has successfully added to a deck
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
