### ISSUE TITLE
Issue 4: User can create new deck lists

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Pegasus-Deck-Builder#4]
## ⚙️ Feature

Users will be able to view saved decks and create new decks

## 📐 Functionality

add a deck view page with a list of saved decks and a button to open a form that creates new decks on that list and page

## 🖼️ Wireframes

![Screenshot 2022-06-13 151546](https://user-images.githubusercontent.com/99226300/173464464-bd8bba47-477e-40fe-ae15-d95a6022b719.jpg)
![2](https://user-images.githubusercontent.com/99226300/173464470-f6eb584a-338e-41dc-b7e6-7290d19888c0.jpg)
![Screenshot 2022-06-13 151723](https://user-images.githubusercontent.com/99226300/173464474-15f53eb0-fbaf-4506-bb05-12d4363306bc.jpg)

## ✅ Task List

- [x] add dropdown select to search results page to hold values of new card deck names
- [x] add new `div[data-view=decks]` to HTML
- [x] declare function in main.js to create new instances of the `decks` object model
    - [x] `name` should be set as parameter
- [x] listen for event listeners on the decks button and card search button in header and use `viewSwap` as a callback
- [x] write layout for deck view into new div in HTML that includes:
    - [x] `h1` that reads "decks"
    - [x] button with the value "new deck+"
    - [x] loads decks with placeholder image out of stored data model on loading
- [x] style for both desktop and mobile using placeholder values
- [x] add view in HTML that shows when a deck is clicked on
- [x] include a return button that uses the viewSwap function to go back to the decks page when clicked
- [x] use mock up to declare a new function that populates DOM tree to decks doing the following:
    - [x] loop through the stored data model for saved card data
    - [x] populate new column-fourth divs that resemble the search results page using properties of cards stored in the selected deck
