### ISSUE TITLE
Issue 5: User can delete cards from deck lists

### ISSUE THREAD

**Issue by NolanReda** [NolanReda/Pegasus-Deck-Builder#5]
## ⚙️ Feature

User can delete cards from a deck list

## 📐 Functionality

add a deck list view page and a button to allow user to select cards with a checkbox to be deleted

## 🖼️ Wireframes

![Screenshot 2022-06-13 152123](https://user-images.githubusercontent.com/99226300/173464596-efae1ad2-7ead-4541-8491-79d60b2d2119.jpg)
![2](https://user-images.githubusercontent.com/99226300/173464600-36b887e2-1b5d-407d-934e-d8a7a032d437.jpg)
![Screenshot 2022-06-13 152249](https://user-images.githubusercontent.com/99226300/173464604-75a4112e-9a30-4c55-b7e5-9286579d29e3.jpg)

## ✅ Task List

- [x] create a function to both remove a selected DOM element from the tree AND splice the data from the data model
- [x] add a modal to confirm choice to delete
- [x] style for desktop and mobile
- [x] get rid of unnecessary code comments and CSS rules
- [x] test in incognito window
- [x] fix all bugs
